### ISSUE TITLE
There is no hydra/MMGNet

### ISSUE THREAD

**Issue by FreemanLi25** [Xihaier/Continuous-Field-Reconstruction-MMGN#1]

**Comment by lizhangyao** [comment]
![1717406830269](https://github.com/Xihaier/Continuous-Field-Reconstruction-MMGN/assets/83164359/2407169e-b68d-43f3-b28a-64aede2ee600)

made it

**Comment by danperazzo** [comment]
I had the same problem! Below is the traceback:

```
Traceback (most recent call last):
  File "/media/danperazzo/Acer/Continuous-Field-Reconstruction-MMGN/main.py", line 48, in <module>
    train()
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
          ^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 573, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 520, in add_child
    subtree_ = _create_defaults_tree_impl(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 488, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/media/danperazzo/Acer/anaconda3/envs/MMGN/lib/python3.11/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'default': Could not find 'hydra/MMGNet'

Available options in 'hydra':
	config
	default
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///media/danperazzo/Acer/Continuous-Field-Reconstruction-MMGN/configs
	provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
	provider=schema, path=structured://
```

**Comment by Xihaier** [comment]
Thanks for the question, everyone. Please switch the Hydra config to `default`. In `configs/default.yaml` (line 3), change:

```yaml
- hydra: MMGNet  # ResMLP SirenNet FFN_P FFN_G MMGNet
```

to:

```yaml
- hydra: default
```

**Comment by danperazzo** [comment]
Thanks a lot!!

I actually managed to run using this stragy.  :)
